services:
  nginx:
    build: ./docker/nginx
    restart: "no"
    depends_on:
      - php-fpm
    volumes:
      - ./src:/var/www:z
    working_dir: /var/www
    environment:
      #change domains
      - VIRTUAL_HOST=domain1.com,domain2.com
      - NGINX_BACK_DOMAIN=domain1.com
      - NGINX_BACK_FOLDER=domain1
      - NGINX_FRONT_DOMAIN=domain2.com
      - NGINX_FRONT_PORT=5173
    networks:
      - app_net
      - nginx-proxy

  mysql:
    image: mysql:8
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/tmp:/tmp:z
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/db:/var/lib/mysql:z
    ports:
      #change first port
      - "33061:3306"
    networks:
      - app_net

  php-fpm:
    build: ./docker/php-fpm
    restart: "no"
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www:z
    working_dir: /var/www
    networks:
      - app_net

  redis:
    image: redis:latest
    restart: "no"
    ports:
      #change first port
      - "63791:6379"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
  nginx-proxy:
    external: true